### ISSUE TITLE
small typo in blog_adaptive_theming_guide

### ISSUE THREAD

**Issue by SunlightBro** [rydmike/rydmike.github.io#4]
While reading through you amazing blog, I found a small typos/issues:

- nothing gets assigned to `borderRadius` https://github.com/rydmike/rydmike.github.io/blob/648cee4f8d9dd23e311bf715cd04b3ec29617312/blog_adaptive_theming_guide.md?plain=1#L124

- "To do so, we ~~as~~ `tones` for" should probably be **use**
https://github.com/rydmike/rydmike.github.io/blob/648cee4f8d9dd23e311bf715cd04b3ec29617312/blog_adaptive_theming_guide.md?plain=1#L160

**Comment by rydmike** [comment]
Thanks @SunlightBro appreciate the keen eye and help with improving the content! 👍🏻
